# Generated by Django 6.0.1 on 2026-01-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_trivia_blog_created_3f07ed_idx_blog_blogpo_created_2e77d7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='signature_valid',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='encrypted_data',
            field=models.TextField(blank=True, help_text='Encrypted fingerprint and content hash'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='encrypted_valid',
            field=models.BooleanField(default=False, help_text='Whether the encryption has been verified'),
        ),
    ]
